### ISSUE TITLE
Septentrio receiver

### ISSUE THREAD

**Issue by xeeee** [tomojitakasu/RTKLIB#130]
Hi,
I saw that there is a file "septentrio.c" that decodes the Septentrio Binary Format, but from what I understood looking for the rest of the code, the sbf functions are still not implemented in the main rtklib.
Am I missing something?
I also tried outputting RCTM3 in the Septentrio, but couldn't get RTKLIB to fully work with it.
Any advice?

Thanks :)

**Comment by tomojitakasu** [comment]
Septentrio is supported in rtklib 2.4.3 b6.

**Comment by xeeee** [comment]
Thanks for the update.
In windows it works fine, i think.
In linux it's not working. Some makefiles were missing some files, but i got it working.
But even after that it still not working.
I think, rtkrcv is still missing sbf in some "fmt" variables.
If I change for #ubx it works fine.

makefiles that needs updates:
str2str needs septentrio
rnx2rtkp needs pop_corr, tides
convbin needs septentrio
rtkrcv needs septentrio, pop_corr, tides

**Comment by JensReimann** [comment]
I recently found some bugs in Septentrio receiver code. 
The attached patch solves 
- issue in ephemeris code for glonass and galileo
- issue in decoding range measurements for 2nd and 3rd frequency

Best regards

[septentrio.patch.txt](https://github.com/tomojitakasu/RTKLIB/files/106814/septentrio.patch.txt)

**Comment by xeeee** [comment]
Even with the patch applied i'm still not able to receive nav/obs messages.
I tried again with the 2.4.3b6 in windows, and I receive the messages and can see the satellites, so my receiver is sending the right data.
Switch back to linux with 2.4.3b6 with that patch, but still no messages.

**Comment by JensReimann** [comment]
I tested Septentrio support both on Windows (64 bit) and Linux (64 bit) with success. On Linux I found that the gcc makefile for rtkrcv is not up-to-date (patch attached). The patch also adds the septentrio option to input file formats.

What application are you using for testing? Are you also using a 64bit OS? Which kind of receiver are you using? I can only test with PolaRxS.

[rtkrcv.patch.txt](https://github.com/tomojitakasu/RTKLIB/files/107967/rtkrcv.patch.txt)
[septentrio_v2.patch.txt](https://github.com/tomojitakasu/RTKLIB/files/107968/septentrio_v2.patch.txt)

**Comment by xeeee** [comment]
I'm using an Septentrio AsteRx4.
With the 2.4.3b8 and your new patches I was able to make it work. I'm receiving all the messages and was able to generate a solution.
I'm getting some "warning: implicit declaration of function..." in the septentrio.c file, but the makefile was able to finish.
But sometimes after I run some commands "status, solution, error, stream, observ...." the program ends with a segmentation fault.
I tested it in a ubuntu 15.04 32bits and in ubuntu 15.04 running in an odroid-xu4

**Comment by JensReimann** [comment]
I added several sanity checks to the code (patch to 2.4.3 and whole file attached). I hope this will solve the crash. There are also other improvements, too.
If you experience more crash try sending a core fil
[septentrio.c.txt](https://github.com/tomojitakasu/RTKLIB/files/112200/septentrio.c.txt)
e (ulimit -c unlimited). This helps debugging a lot.

[septentrio_v3.patch.txt](https://github.com/tomojitakasu/RTKLIB/files/112196/septentrio_v3.patch.txt)

**Comment by xeeee** [comment]
I think it's working but I need to check again somewhere with better visibility.
Now somethings I've found...
When trying a single or PPP solution:
1 - If i run your V2 patch, rtkrcv is able to "see" 14 satellites. If I stop it, and run the V3 patch using the same .conf file, it will only see 5 satellites.
2 - If I run the command "observ", it will show the 14 or 5 described satellites, if I run the command "satellite", it doesn't show anything.
3 - I wasn't able to get a solution today. Maybe because of point 2!? It was strange because in the septentrio webpage I was getting a fix and a lot of satellites.

Kinematic Solution:
- Used str2str to create a tcpserver for the septentrio. Worked fine.
- RTKLIB in windows was able to get a float/fix solution.

Tomorrow, I will try in linux. Another thing, It's possible to pass the base station position (Septentrio) with messages, like with the RTCM Option?

**Comment by JensReimann** [comment]
There was a bug in v3 selecting valid ephemeris when option -EPHALL was not set. It is fixed now. But at least the crash was gone with that version.
[septentrio.c.txt](https://github.com/tomojitakasu/RTKLIB/files/115728/septentrio.c.txt)

Concerning your last question: The Septentrio receiver knows much more than it delivers to RTKLIB, e.g. its position or configured antenna offsets. Unfortunately, I have no idea how to pass it to RTKLIB.

**Comment by xeeee** [comment]
It seems the segmentation fault it's still present.
After loading the .conf file and doing the restart, there's a crash.
Maybe, it's a problem with my .conf file.

I've attached the .conf file I'm using and 2 core dump files.
About the Receiver options you talked, I'm using the default options in the 2.4.3b8 makefiles, should I change something?

[files.zip](https://github.com/tomojitakasu/RTKLIB/files/116176/files.zip)

**Comment by JensReimann** [comment]
Unfortunately the core files did not include any useful information. So you may have to run a debugger by yourself to find the reason for the crash. 
The attached version is nearly feature complete. I tested everything I could. Since I have no access to Beidou and QZSS I disabled those code paths. Maybe your crash appeared somewhere there and is now gone.
Again: with this code you cannot use Beidou or QZSS.
[septentrio.c.txt](https://github.com/tomojitakasu/RTKLIB/files/119396/septentrio.c.txt)

**Comment by ThomasKrausUniBwM-ISTA** [comment]
Dear @JensReimann, 
Thanks for sharing your update of "septentrio.c.txt". There is another "real" reason for the crash. You avoided the crash by adding "if (alm.sat == 0) return -1;" to the function **"decode_galalm"**. 

The "real" reason is because of reading the wrong alm.sat in line 1463 of "septentrio.c.txt". You should substract with 70:
- alm.sat =   satno(SYS_GAL,U1(p + 49)**-70**);

**Comment by JensReimann** [comment]
You are completely right. I fixed this issue. A new version including also several other bug fixes is attached.
[septentrio.c.txt](https://github.com/tomojitakasu/RTKLIB/files/206476/septentrio.c.txt)

**Comment by tomojitakasu** [comment]
Thanks.
Your septentrio.c is imported to 2.4.3 b10.
